# Should be the INDEX DIGEST from an image tagged `bookworm-<DATE>-slim`:
#     https://hub.docker.com/_/debian/tags?name=trixie-
#
# Tag for this digest: trixie-20260518-slim
DEBIAN_IMAGE_DIGEST=sha256:b6e2a152f22a40ff69d92cb397223c906017e1391a73c952b588e51af8883bf8
# Can be bumped to today's date
DEBIAN_ARCHIVE_DATE=20260610
# Can be bumped to the latest date in https://github.com/google/gvisor/tags
GVISOR_ARCHIVE_DATE=20260601

# Buildkit image (taken from freedomofpress/repro-build)
#
# These images do NOT need to be bumped, since the `check-reproducibility` CI
# job verifies the result of this Buildkit version against the latest one.
BUILDKIT_IMAGE="docker.io/moby/buildkit:v0.23.2@sha256:ddd1ca44b21eda906e81ab14a3d467fa6c39cd73b9a39df1196210edcb8db59e"
BUILDKIT_IMAGE_ROOTLESS="docker.io/moby/buildkit:v0.23.2-rootless@sha256:cab936745de5d673465948f1e93ff4d6e372bbe33f218afd3314eba45a6f85a9"
